#!/bin/zsh -eu

instance_ssh_config=${argv[1]}
remote_command=${argv[2]}

echo "${0:a:h} prepared to read ssh config: ${instance_ssh_config}"
source $instance_ssh_config

run () {
    ssh -i ${ssh_identity_file} ${ssh_user}@${ssh_host} $1
}

echo "preparing to run ${remote_command}"
run "${remote_command}"
